### ISSUE TITLE
Templated rules always shows change to apply

### ISSUE THREAD

**Issue by sjparkinson** [signalsciences/terraform-provider-sigsci#152]
I am looking to manage all templated rules using Terraform.

To start we will have a number of them disabled, but we're finding the following always results in changes when running `terraform plan`. Seems like after `terraform apply` some state isn't getting saved that'd be needed to avoid there being a change.

```hcl
resource "sigsci_site_templated_rule" "disabled_ato_templated_rules" {
  for_each = toset([
    "LOGINATTEMPT",
    "LOGINFAILURE",
    "LOGINSUCCESS",
    "REGATTEMPT",
    "REGFAILURE",
    "REGSUCCESS",
  ])

  name            = each.key
  site_short_name = "..."

  detections {
    enabled = false
  }
}
```

After running `terraform apply` the state from `terraform state show 'sigsci_site_templated_rule.disabled_ato_templated_rules["LOGINATTEMPT"]'` looks like:

```hcl
resource "sigsci_site_templated_rule" "disabled_ato_templated_rules" {
    id              = "LOGINATTEMPT"
    name            = "LOGINATTEMPT"
    site_short_name = "..."
}
```

**Comment by richard-wilhite** [comment]
+1 I see the same. We have a templated rule that is already enabled, which terraform wants to enable again.

**Comment by merdaczatcf** [comment]
+1 same here. Any tentative plan to fix this?

**Comment by daniel-corbett** [comment]
Hi @sjparkinson - apologies for the delay here. Your specific issue is because at the moment the API requires that `fields` is specified. When `fields` is missing, it is resulting in a Validation Error. I will talk with the team behind the API and see if it's possible to relax the requirement of `fields` when `enabled = false`. Separately, I also think these validation errors that are being returned may need to return a 4xx error code.

Until then, you can solve this by using the following:

```
resource "sigsci_site_templated_rule" "disabled_ato_templated_rules" {
  for_each = toset([
    "LOGINATTEMPT",
    "LOGINFAILURE",
    "LOGINSUCCESS",
    "REGATTEMPT",
    "REGFAILURE",
    "REGSUCCESS",
  ])

  name            = each.key
  site_short_name = "..."

  detections {
    enabled = false 
    fields {
      name  = "path"
      value = "/nonexistent"
    }
  }
}

```

**Comment by daniel-corbett** [comment]
@richard-wilhite - I am unable to duplicate the issue of when a Templated Rule is enabled that terraform continuously tries to update it. Can you please provide a sample of the terraform config with the steps to duplicate this issue?

@merdaczatcf - are you having the issue with continuous disabling or continuous enablement? If disablement, please see my comment above. If enablement, please provide a sample of your terraform config to reproduce.

**Comment by tdysko-cf** [comment]
@daniel-corbett sorry for late response, we are trying to enable LOGINATTEMPT and REGATTEMPT, but what I realized after reading this thread is that we might have missed the path, and without it the enablement won't work, am I right? 
That may be an improvement idea for validation, but if this is a case I don't think we have a issue here, we'll just fill the paths.

**Comment by magmax** [comment]
@daniel-corbett I'm using terraform provider 2.1.6 and same happens.

This happens to me when I remove the required fields, despite I'm disabling the templated rule.

Example:
```
resource "sigsci_site_templated_rule" "loginfailure" {
  site_short_name = "example"
  name            = "LOGINFAILURE"

  detections {
    enabled = true
    fields {
      name  = "path"
      value = "/auth/*"
    }
    fields {
      name  = "responseCode"
      value = "302"
    }
  }
}                                                       
```
Apply it and then change it into:
```
resource "sigsci_site_templated_rule" "loginfailure" {
  site_short_name = "example"
  name            = "LOGINFAILURE"

  detections {
    enabled = false
  }
}                                                       
```

And the plan will be dirty until fields are re-added.

**Comment by magmax** [comment]
I've tested changing the resource name, and the problem persists despite the resource is being destroyed and re-created, so probably it is something happening at server level.

The only bypass I've found is to preserve the fields with any value even after disabling the rule.

**Comment by daniel-corbett** [comment]
Hi @magmax - I looked into this a bit and can confirm the issue that you are encountering. We will look into it and get back to you once we have a fix.

**Comment by daniel-corbett** [comment]
Hi @magmax, so I dug into this a bit more

> The only bypass I've found is to preserve the fields with any value even after disabling the rule.

At the moment, this is not a bypass and actually the correct way to perform the update. The API expects that the Templated Rule has the response code + path specified. If you attempt to make the changes you are making within the UI it will prompt with a note that those fields are required.

We will continue to investigate other options but for now this goes back to my [original comment above](https://github.com/signalsciences/terraform-provider-sigsci/issues/152#issuecomment-1609609373).

**Comment by magmax** [comment]
Thank you for revieweing, @daniel-corbett !

If the only way to handle this problem is by defining all the mandatory fields, that might be documented, probably.

**Comment by daniel-corbett** [comment]
Hi all, we have deployed a server side fix that should fix the issue you have been encountering here. Please let me know if you have any additional questions/feedback. Thanks!

cc: @sjparkinson @richard-wilhite @merdaczatcf @tdysko-cf @magmax
