### ISSUE TITLE
Missing `requestlogging` argument from `sigsci_corp_rule`

### ISSUE THREAD

**Issue by sjparkinson** [signalsciences/terraform-provider-sigsci#157]
It looks like there's a missing argument to disable request sampling on Corp rules in the `sigsci_corp_rule` resource.

This is available in the `sigsci_site_rule` resource.

**Comment by richard-wilhite** [comment]
I think this is actually a limitation of the API https://docs.fastly.com/signalsciences/api/#_corps__corpName__rules_post. I don't see `requestlogging` as an option for the body parameters in the API doc.

**Comment by shawnps** [comment]
@sjparkinson we added the `requestlogging` to corp rules in the latest version `v1.2.28`:

https://github.com/signalsciences/terraform-provider-sigsci/releases/tag/v1.2.28

Could you please try that version and reopen this issue if it doesn't work as expected? Thank you!
