### ISSUE TITLE
Unable to enable some templated rules through terraform

### ISSUE THREAD

**Issue by CalvinKim-at** [signalsciences/terraform-provider-sigsci#16]
For example AWS-SSRF templated rule has an empty field value. But field is required in terraform schema.

**Comment by willnewby** [comment]
I would also love to see this implemented/updated.

**Comment by v1sion** [comment]
encounter the same issue.

**Comment by alfred-sigsci** [comment]
Hello, sorry for the delay in response but we will be looking at this for the next release we are planning in early 2021.
