### ISSUE TITLE
sigsci_corp_rule resource, does not successfully set the value of the 'requestlogging' optional field

### ISSUE THREAD

**Issue by appsrc-eng** [signalsciences/terraform-provider-sigsci#178]
[sigsci_corp_rule resource](https://registry.terraform.io/providers/signalsciences/sigsci/latest/docs/resources/corp_rule), does not successfully set the value of the [requestlogging](https://registry.terraform.io/providers/signalsciences/sigsci/latest/docs/resources/corp_rule#requestlogging) optional field. By default the value will be set to 'sampled', regardless of the actual value provided. Any updates attempting to change the 'requestlogging' field for a particular corp rule will appear successful (via the Terraform CLI); however, will not reflect the appropriate value in the SigSci console (the original value remains).

**Versions:** 
- Terraform: 1.4.4
- SigSci Provider: 1.2.27

**Steps to Reproduce:**
1) Create a custom signal tag
2) Create a rule for any type of request (in this case against any path) - used to force the sigsci agent to log all requests and responses to a local log (e.g. /dev/stdout)
	- set the field of 'requestlogging' to 'none'
3) Apply Terraform
4) Observe outcome in the cloud console
	- the value associated to 'requestlogging' (under _Details_) should incorrectly reflect 'sampled'</br>

**_[Inverse]_**
&nbsp;&nbsp;  5) Change the value associated to 'requestlogging' in the console to 'none' and 'sampled' in Terraform code (i.e. inverse)
&nbsp;&nbsp;  6) Rerun Terraform to pickup the inconsistency and attempt to correct it
&nbsp;&nbsp;  7) Observe no change in the cloud console

**TF Example:**
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.xx_sigsci_corp.sigsci_corp_rule.sigsci_corp_path_rule["70f815787896cf7eaa2c181f6c30ed7f1b7492be86fdc8cfc3a4346ca922a5fb"] will be updated in-place
  ~ resource "sigsci_corp_rule" "sigsci_corp_path_rule" {
        id               = "647e2bd1a1ee1701d5e22518"
      ~ requestlogging   = "sampled" -> "none"
        # (6 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions in workspace "prod"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.xx_sigsci_corp.sigsci_corp_rule.sigsci_corp_path_rule["70f815787896cf7eaa2c181f6c30ed7f1b7492be86fdc8cfc3a4346ca922a5fb"]: Modifying... [id=647e2bd1a1ee1701d5e22518]
module.xx_sigsci_corp.sigsci_corp_rule.sigsci_corp_path_rule["70f815787896cf7eaa2c181f6c30ed7f1b7492be86fdc8cfc3a4346ca922a5fb"]: Modifications complete after 1s [id=647e2bd1a1ee1701d5e22518]
```

**Comment by shawnps** [comment]
Hi @appsrc-eng, thanks for raising this issue. It should be fixed in the latest version `v1.2.28`. 

Could you please try again with `v1.2.28` and reopen this issue if it you still encounter the problem? Thank you!

**Comment by chenrui333** [comment]
@shawnps is this desired per the provider upgrade?
```
  ~ resource "sigsci_corp_rule" "xxxx" {
        id               = "xxx"
      - requestlogging   = "none" -> null
        # (6 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }
```

**Comment by appsrc-eng** [comment]
> Hi @appsrc-eng, thanks for raising this issue. It should be fixed in the latest version `v1.2.28`.
> 
> Could you please try again with `v1.2.28` and reopen this issue if it you still encounter the problem? Thank you!

@shawnps, v1.2.28 is working great, thanks for the prompt resolution!

**Comment by shawnps** [comment]
@chenrui333 sorry about that -- no, that shouldn't happen. I will try to reproduce the issue.

**Comment by shawnps** [comment]
> @shawnps is this desired per the provider upgrade?
> 
> ```
>   ~ resource "sigsci_corp_rule" "xxxx" {
>         id               = "xxx"
>       - requestlogging   = "none" -> null
>         # (6 unchanged attributes hidden)
> 
>         # (3 unchanged blocks hidden)
>     }
> ```

@chenrui333 is this output the result of removing `requestlogging = "none"` from your TF? I'm having trouble reproducing the issue and doing that was the only way I could get this output to occur.

If so, I'd suggest leaving `requestlogging = "none"` in the TF if that matches the rule in the console.

**Comment by chenrui333** [comment]
> > @shawnps is this desired per the provider upgrade?
> > ```
> >   ~ resource "sigsci_corp_rule" "xxxx" {
> >         id               = "xxx"
> >       - requestlogging   = "none" -> null
> >         # (6 unchanged attributes hidden)
> > 
> >         # (3 unchanged blocks hidden)
> >     }
> > ```
> 
> @chenrui333 is this output the result of removing `requestlogging = "none"` from your TF? I'm having trouble reproducing the issue and doing that was the only way I could get this output to occur.
> 
> If so, I'd suggest leaving `requestlogging = "none"` in the TF if that matches the rule in the console.

no, it is not. let me see if I can turn on the debug log and find out why.

**Comment by chenrui333** [comment]
My bad, I forgot to uncomment the code, all good now.

**Comment by shawnps** [comment]
@chenrui333 no problem, thanks for the update 👍
