### ISSUE TITLE
About `sigsci_corp_allowlist`

### ISSUE THREAD

**Issue by chenrui333** [signalsciences/terraform-provider-sigsci#183]
This is more like a question, I only sae `sigsci_site_allowlist` but no `sigsci_corp_allowlist`, any reason why that does not exist? Thanks!

**Comment by daniel-corbett** [comment]
Hi @chenrui333 - apologies for the delay here. My understanding is that the allow list functionality on the Site level was introduced at a time when neither Lists nor Corp level rules were available. Once the concept of "Corp Rules" was introduced it came with both "Corp Lists" and "Site Lists", which are a more flexible version of the existing "allow list" functionality.
