### ISSUE TITLE
Use same Fastly Key env var as the Fastly Terraform provider

### ISSUE THREAD

**Issue by sjparkinson** [signalsciences/terraform-provider-sigsci#188]
This provider uses `FASTLY_KEY`, while the Fastly Terraform provider uses `FASTLY_API_KEY`.

It'd be helpful if the two providers used the same environment variable!

**Comment by ponkio-o** [comment]
Hi @sjparkinson,

v2.0.0 now supports this feature.
https://github.com/signalsciences/terraform-provider-sigsci/pull/189
