### ISSUE TITLE
Impotrt command for site : Unable to find site id for existing resource

### ISSUE THREAD

**Issue by mmdiago** [signalsciences/terraform-provider-sigsci#21]
Terraform import for site resource requires the `id` as input : 

`terraform import sigsci_site.test id`

However, neither in the console, nor in the API (https://docs.signalsciences.net/api/#_corps__corpName__sites__siteName__get) can provide those id for existing site.

Testing with site `shortname` doesn't work too.

How can we find the `id` of existing sites, to use them in `Terraform import` command ?

**Comment by geriruskova** [comment]
Hi! Will this be looked at? I used the exactly the same `shortname ` for the site as it is supposed to be the id used in the url, and got the same error of non-existent site.

**Comment by paulstakem** [comment]
> Terraform import for site resource requires the `id` as input :
> 
> `terraform import sigsci_site.test id`
> 
> However, neither in the console, nor in the API (https://docs.signalsciences.net/api/#_corps__corpName__sites__siteName__get) can provide those id for existing site.
> 
> Testing with site `shortname` doesn't work too.
> 
> How can we find the `id` of existing sites, to use them in `Terraform import` command ?

Hi @mmdiago `short_name` and `id` are the same.

For your example this will work
```
terraform import sigsci_site.test test
```

Which can be confirmed in the terraform state.
```
terraform state show sigsci_site.test
# sigsci_site.test:
resource "sigsci_site" "sites" {
    agent_level            = "log"
    block_duration_seconds = 86400
    block_http_code        = 406
    display_name           = "Test"
    id                     = "test"
    short_name             = "test"
}
```

I hope this helps.

**Comment by mmdiago** [comment]
Hi yes, it works. My issue was on the authentication, but the error message just indicated `site not found` rather than one on the real issue as it's the case when we import corp rule (`need to be connect to use this API`)
