### ISSUE TITLE
Not Comfortable Upgrading to `v3.0.0`

### ISSUE THREAD

**Issue by RoseSecurity** [signalsciences/terraform-provider-sigsci#219]
# Overview

Since the change to add support for non-IP client identifiers within rate limit rules, we have had to pin the provider to version `2.1.8` because updating our existing rules in state is not feasible with our current pipeline configuration. Will this limitation always be a permanent blocker for us? We do not believe it is good practice to remove and import existing rules into state. Even with the provided script, we are not comfortable with this approach as it goes against our use of a controlled and tested deployment process.

**Comment by daniel-corbett** [comment]
Hi @RoseSecurity - adding support for non-IP client identifiers required converting from a `TypeMap` to a `TypeSet`. We did a lot of research into how to best handle this and how it's handled in other providers. Ultimately, the solution we documented (while not ideal) ended up being the cleanest solution for migrating over.

> Will this limitation always be a permanent blocker for us?

Unless a better option is surfaced - yes. We intentionally incremented the major version to signify that it was a breaking change and allow users to pin to the previous version.

> Even with the provided script, we are not comfortable with this approach as it goes against our use of a controlled and tested deployment process.

While I cannot offer much insight here I can tell you that we tested extensively internally and have customers who migrated over without any issue.  I would always suggest to make backups of your terraform state as well as testing on a non-prod site that simulates your production configuration.

Sorry for the inconvenience here and if you have any suggestions as to how we could have better handled a conversion of `TypeMap` to `TypeSet` we are open to suggestions.
