### ISSUE TITLE
Corp rule update Error: Update failed for rule ID xxxx

### ISSUE THREAD

**Issue by mmdiago** [signalsciences/terraform-provider-sigsci#28]
With the version 0.3.0 of the provider, we are not able to update corp rule. Any change by adding new signal, or sites end up with this failure message : 

```Error: Update failed for rule ID xxxxxx.
got:
sigsci.CreateCorpRuleBody{SiteNames:[]string{"c", "s", "t"}...}
expected:
sigsci.CreateCorpRuleBody{SiteNames:[]string{"s", "c", "t"}...}
```

A replace here the sites names, but it seems that the compare failed just because of the sites names order differs

**Comment by mmdiago** [comment]
I think the issue need a fix as the usage of method `reflect.DeepEqual` [here](https://github.com/signalsciences/terraform-provider-sigsci/blob/2e9983046336f9b52ef8f84b7f549f880d3904ba/provider/resource_corp_rule.go#L246 ) is not adequate to compare here the string array (example for SiteNames, when items are at different position in array. It seems that the returned list is sorted : causing the comparison failure).

**Comment by mmdiago** [comment]
I think the issue need a fix as the usage of method `reflect.DeepEqual` [here](https://github.com/signalsciences/terraform-provider-sigsci/blob/2e9983046336f9b52ef8f84b7f549f880d3904ba/provider/resource_corp_rule.go#L246 ) is not adequate to compare here the string array (example for SiteNames, when items are at different position in array. It seems that the returned list is sorted : causing the comparison failure).

**Comment by jhanrahan-sigsci** [comment]
You were right, confirmed this works like it should and it was just the deepEquals check that was wrong. I've removed those checks as they should not be necessary
