### ISSUE TITLE
[Documentation] Add  actions type "addSignal"

### ISSUE THREAD

**Issue by ponkio-o** [signalsciences/terraform-provider-sigsci#33]
Hi.

I found that some of the explanations in [site_rule.md](https://github.com/signalsciences/terraform-provider-sigsci/blob/master/docs/resources/site_rule.md) were missing.
Specifically, `addSignal` is missing from the description of actions in [site_rule.md](https://github.com/signalsciences/terraform-provider-sigsci/blob/master/docs/resources/site_rule.md).

I was a bit confused when setting up the rule, so I proposal adding it to the documentation.

**Comment by jhanrahan-sigsci** [comment]
I have updated the docs to hopefully clarify this a bit, please let us know if you have other suggestions!
