### ISSUE TITLE
Plan is created with invalid credentials

### ISSUE THREAD

**Issue by elblivion** [signalsciences/terraform-provider-sigsci#43]
Tested with plugin version v0.4.3, Terraform v0.14.11

The provider happily creates a plan with invalid credentials, which if applied (a) fails (b) can delete valid resources from state.

Expected behaviour: 
* Terraform should refuse to create a plan if the provider is unable to authenticate.
* Resources are not deleted from state when the wrong credentials are provided.

To reproduce:

```
provider "sigsci" {}
resource "sigsci_site" "test" {
  short_name             = "test-tf"
  display_name           = "Test"
  block_duration_seconds = 86400
  agent_anon_mode        = ""
  agent_level            = "block"
}

terraform {
  required_version = ">= 0.13"
  required_providers {
    sigsci = {
      source = "signalsciences/sigsci"
    }
  }
}
```

Apply the configuration with correct authentication:
```
sigsci_site.test: Creating...
sigsci_site.test: Creation complete after 2s [id=test-tf]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
$ terraform state list
sigsci_site.test
```
Set some invalid authentication parameters:

```
$ cat .envrc 
PATH_add ../../../bin
export SIGSCI_EMAIL=foo
export SIGSCI_TOKEN=bar
export SIGSCI_CORP=baz
```

Plan/apply with incorrect authentication parameters:
```
$ terraform apply
sigsci_site.test: Refreshing state... [id=test-tf]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # sigsci_site.test will be created
  + resource "sigsci_site" "test" {
      + agent_level            = "block"
      + block_duration_seconds = 86400
      + block_http_code        = (known after apply)
      + display_name           = "Test"
      + id                     = (known after apply)
      + primary_agent_key      = (known after apply)
      + short_name             = "test-tf"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

sigsci_site.test: Creating...

Error: Unauthorized: You must be logged in to call this API

  on sigsci_sites.tf line 1, in resource "sigsci_site" "test":
   1: resource "sigsci_site" "test" {

```
State is wiped:

```
$ terraform state list
$
```

**Comment by loxal** [comment]
Hey @elblivion, thanks a lot for this issue report. Still with `Terraform v1.0.7` I could not reproduce the issue. It might be related to an issue in and **older version of Terraform** itself and not to the plugin.

Also `.envrc` seems to be ignored in the mentioned Terraform version as you see below as I had to enter some of the credentials interactively.

![Screenshot from 2021-09-20 10-35-02](https://user-images.githubusercontent.com/87507/133975649-a0b03077-b15b-4d97-a918-4ed03f05a9fe.png)

**Comment by elblivion** [comment]
Hi @loxal , weird that we don't get this with other providers. It's your call as to whether to spend time on fixing this, in our case we're not yet ready to go to Terraform 1.0 and it might be the case of other folks too.

Sorry, I should have specified that I was using [direnv](https://direnv.net/) to manage environment variables, I included that just to illustrate that I was modifying the config.

The error Terraform logs is this:

```
2021-09-20T08:08:00.612Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"                                                                                                                      
2021-09-20T08:08:00.613Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/signalsciences/sigsci/0.4.3/linux_amd64/terraform-provider-sigsci_v0.4.3 pid=42                                                                       
2021-09-20T08:08:00.613Z [DEBUG] plugin: plugin exited                 
```

So I guess this was fixed in https://github.com/hashicorp/terraform/pull/26694. Weird that you do not see any error when planning with invalid credentials though, IMHO if a plan is still created this is a problem.

**Comment by loxal** [comment]
@elblivion sure, I understand your migration concerns as I remember migrating code for one of the pre-1.0 versions.

I think missing `direnv` was not the issue as wrong credentials can be passed in several ways. The issue was rather the combination of our plugin and a pre-1.0 Terraform version.

I see an authentication issue when doing `terraform plan` but fixing the credentials subsequently and running `terraform apply` does not corrupt the state:

![Screenshot from 2021-09-22 05-54-34](https://user-images.githubusercontent.com/87507/134281180-4608f442-9b4c-4706-86aa-9938d574b298.png)

I agree that a *new plan* should not be created once terraform fails an operation. However I am afraid I wouldn't be able to justify a major prio for fixing this issue as you are using an older version and there is a "workaround" available (not using wrong credentials). I know, from a usability point of view it's not perfect.

**Comment by jbhanrahan** [comment]
Sorry for looking at this late, but the solution for this seemed to be pretty easy so I will include it in the next release as I think this is a good idea. Although I couldn't corrupt the state either as @loxal said, the provider is getting confused and behaving incorrectly.

**Comment by majormoses** [comment]
Just chiming in that we have seen strange behavior as well regarding sigsci running a plan when it fails authentication and we are on `1.x`. I am not sure if I have seen it recently but I am not sure if that is because auth is being provided properly in our execution environment.
