### ISSUE TITLE
Data source for CloudWAF instance, or specific deployments

### ISSUE THREAD

**Issue by ohookins** [signalsciences/terraform-provider-sigsci#47]
Similar to how the Fastly provider has https://registry.terraform.io/providers/fastly/fastly/latest/docs/data-sources/ip_ranges data source for retrieving IP ranges (e.g. for allow-listing IP addresses in firewalls, security groups etc), it would be very handy to have the same functionality in the SigSci provider for the same purpose

Apparently the `get /corps/{corpName}/cloudwafInstances/{deployment_id}` endpoint would return all of the deployments which can be iterated over to get their respective egress IPs... I'm not sure if starting at the top-level and drilling down is better, or just having a data source for deployments directly (or maybe both) would be a better option. But in either case, a data source to get egress IPs in some manner is necessary.

Since they are per-customer and require authentication it's not as straightforward as just using the http provider and hitting a given endpoint. API authed sessions are required so I think this puts it a bit outside of workaround territory with standard built-ins in Terraform.

**Comment by jhanrahan-sigsci** [comment]
We are looking to add cloudwaf support in the future, I will note this as a feature to include, thanks!
