### ISSUE TITLE
Support the use of custom response codes in site and corp rules

### ISSUE THREAD

**Issue by majormoses** [signalsciences/terraform-provider-sigsci#49]
Some organizations may want to set specific response codes for all or specific requests.

https://docs.fastly.com/signalsciences/using-signal-sciences/features/custom-response-codes/

**Comment by shawnps** [comment]
@majormoses thank you for the issue -- it looks like we do support custom response codes for site rules, with `response_code` inside the `actions` field:

```
  actions {
    type          = "block"
    response_code = 499
  }
```

Unfortunately corp rules don't support custom response codes, I can pass that request on to the team.

Please feel free to reopen the ticket if I misunderstood anything 👍
