### ISSUE TITLE
Cannot update sigsci_site_integration.agent_changes with provider

### ISSUE THREAD

**Issue by gwensmu** [signalsciences/terraform-provider-sigsci#50]
When using provider version 0.4.3 (`parallelism=1`) to update a mailing list integration to update on agent changes, I run into the following error:

```
Terraform will perform the following actions:

  # sigsci_site_integration.agent_changes will be updated in-place
  ~ resource "sigsci_site_integration" "agent_changes" {
        events          = [
            "agentAlert",
            "loggingModeChanged",
        ]
        name            = "Mailing List"
        site_short_name = "redacted"
        type            = "mailingList"
      ~ url             = "me@redacted.com" -> "dev@redacted.com"
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

sigsci_site_integration.agent_changes: Modifying... [id=redacted]

Error: Provider produced inconsistent result after apply

When applying changes to sigsci_site_integration.agent_changes, provider
"registry.terraform.io/signalsciences/sigsci" produced an unexpected new
value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

**Comment by majormoses** [comment]
I agree its a bug in the provider and it seems to only affect some resources. It does appear that they have a documented work around here: https://github.com/signalsciences/terraform-provider-sigsci/blob/d93757a951c0e4409c81bf9f7478f10099b84e59/docs/resources/site_integration.md#example-usage have you tried setting the `parallelism=1` option on apply? We recently imported our existing setup into terraform and have been dancing around using some of these resources that require this being set though we decided to bite the bullet with templated rules and are hoping that it remains stable. I do also wonder if it's possible that this is somehow related to #43. I have seen stranger things when auth contexts get lost in multi threaded processes.

**Comment by gwensmu** [comment]
@majormoses yep I have been running all applies with `-parallelism=1` - solves most of the issues but not this one. I'll add that to the issue description.

**Comment by majormoses** [comment]
@jmvbxx looks like we may have dodged a bullet in delaying pulling those into terraform.

**Comment by majormoses** [comment]
Out of curiosity do you see these on creation or only on an update?

**Comment by gwensmu** [comment]
I had created the agent_changes integration manually via the GUI and was attempting to update after importing the resource into terraform

**Comment by majormoses** [comment]
Unfortunately I think at the moment you're gonna have to back out your config and `state rm` to get into a clean state. I don't have enough golang knowledge to be of much use in actually fixing the bug. It would be helpful to know if the same issue exists for an integration that was created by the provider. It may help limit the amount of code needed to be scanned to locate the bug.

**Comment by shawnps** [comment]
Hello, I think I found the cause of this issue. It appears to be specific to updating mailing list integrations. 

The API returns an error when updating a mailing list integration, but this error wasn't returned in the TF, so we couldn't see the failure when applying the update:

https://github.com/signalsciences/terraform-provider-sigsci/pull/115

The PR above fixes the missing error return. The actual fix for updating a mailing list integration will have to happen either in the Go client or the API. I'll follow up on this ticket when the fix is released.

**Comment by shawnps** [comment]
Hi, we've deployed a fix to the API and I was able to update a mailing list integration successfully. Please reopen this issue if you still encounter this problem. Thank you!

**Comment by gwensmu** [comment]
cc @jonhoman
