### ISSUE TITLE
sigsci_corp_rule inList Bug

### ISSUE THREAD

**Issue by KodMishka** [signalsciences/terraform-provider-sigsci#51]
Hi, 

When trying to use a corp list in a corp rule with the below configuration 
```
resource "sigsci_corp_rule" "test" {
    site_short_names = []
    type = "request"
    corp_scope = "global"
    reason = "Allow requests from proxy IPs"
    enabled = true
    expiration = ""
    group_operator = "any"
    conditions {
        type = "single"
        field = "ip"
        operator = "inList"
        value = sigsci_corp_list.proxies.name
    }
    actions {
        type = "allow"
    }
}
```

I get the below provider error 

> "registry.terraform.io/signalsciences/sigsci" produced
│ an invalid new value for .conditions: planned set element
│ cty.ObjectVal(map[string]cty.Value{"conditions":cty.SetValEmpty(cty.Object(map[string]cty.Type{"conditions":cty.Set(cty.Object(map[string]cty.Type{"field":cty.String,
│ "group_operator":cty.String, "operator":cty.String, "type":cty.String, "value":cty.String})), "field":cty.String, "group_operator":cty.String, "operator":cty.String,
│ "type":cty.String, "value":cty.String})), "field":cty.StringVal("ip"), "group_operator":cty.StringVal(""), "operator":cty.StringVal("inList"),
│ "type":cty.StringVal("single"), "value":cty.StringVal("Proxy allowlist")}) does not correlate with any element in actual.

I have tried using other `sigsci_corp_list` attributes ("id" and "entries") but they lead to an internal error. There are no errors with the `sigsci_corp_list` resource and it is provisioned as normal in the sigsci dashboard.

**Comment by shawnps** [comment]
Hi @KodMishka, thanks for the issue.

I created a corp list in the UI and then a corp rule with the following TF:

```
resource "sigsci_corp_rule" "test-rule" {
  site_short_names = []
  type             = "request"
  corp_scope       = "global"
  group_operator   = "any"
  enabled          = true
  reason           = "Test reason"
  expiration       = ""

  conditions {
    type     = "single"
    field    = "ip"
    operator = "inList"
    value    = "corp.testlistname"
  }

  actions {
    type = "allow"
  }
}
```

I suspect the issue may be with `conditions.value`:

```
value = sigsci_corp_list.proxies.name
```

as I was unable to create a corp list with that ID (validation fails when trying to use a period in the name, and it looks like IDs for corp lists default to `corp.[name]`).

Could you please confirm that the corp list name is correct in the `value` field, and try creating the rule with the latest release `v1.2.2`? Thanks!

**Comment by shawnps** [comment]
@KodMishka creating a list and corp rule worked for me on hte latest provider version (`1.2.4`) using `value = sigsci_corp_list.proxies.id` rather than `value = sigsci_corp_list.proxies.name`.

If you try with the latest version and it still doesn't work, please reopen this issue. Also it would be helpful to see `sigsci_corp_list.proxies` if you can anonymize and provide it. Thank you!
