### ISSUE TITLE
FORCEFULBROWSING signal missing from rule validation logic

### ISSUE THREAD

**Issue by KodMishka** [signalsciences/terraform-provider-sigsci#52]
```
conditions {
  field = "signalType"
  operator = "equals"
  type = "single"
  value = "FORCEFULBROWSING"
}
```
Returns warning 

> Validation failed - invalid value for signalType: FORCEFULBROWSING

**Comment by jbhanrahan** [comment]
Its a little confusing, but this is actually an error forwarded from the API and not a validation done on the terraform side.  Its hard to tell with the little snippet you provided, but try signal = "FORCEFULBROWSING" on the top level
