### ISSUE TITLE
Error: Incompatible provider version -  M1 - darwin_arm64

### ISSUE THREAD

**Issue by virtualjj** [signalsciences/terraform-provider-sigsci#56]
First, thanks for the provider!

However, unfortunately getting the error below since no package for `darwin_arm64` available:

```
Initializing provider plugins...
- Finding hashicorp/aws versions matching "3.67.0"...
- Finding latest version of signalsciences/sigsci...
- Installing hashicorp/aws v3.67.0...
- Installed hashicorp/aws v3.67.0 (signed by HashiCorp)
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/signalsciences/sigsci v0.4.3 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider
│ may have different platforms supported.
```

Many at my org are moving to M1 Macs so when available for M1, will make things a bit easier. In the meantime, will use a compatible platform.

**Comment by amtux** [comment]
Hey I just updated go version to 1.17 which added support for M1 `darwin_arm64`.
Please validate [0.4.4](https://github.com/signalsciences/terraform-provider-sigsci/releases/tag/v0.4.4) works on your machine.

**Comment by virtualjj** [comment]
Thank you very much - works now!
