### ISSUE TITLE
"clientIdentifiers" for specifying multiple Client Identifier for Rate Limit rule doesn't seem to be supported.

### ISSUE THREAD

**Issue by Charlie-I** [signalsciences/terraform-provider-sigsci#60]
From the UI, one can set up multiple user identifiers for counting rates (eg: IP, IP + Cookie Value, Signal Payload Value, ...). We don't see, to have the same capability in Terraform. Trying to do so throws the below error. 

`│ Inappropriate value for attribute "rate_limit": element "clientIdentifiers": string required.`

**Comment by mb38291** [comment]
Is anyone looking into adding this functionality?

**Comment by loxal** [comment]
There is an [internal ticket to track the progress](https://fastly.atlassian.net/browse/SECURE-111).

**Comment by loxal** [comment]
@tdysko-cf this enhancement request is in our backlog but unfortunately I cannot provide you with with a timeline. Reaching out via official [support channels](https://dashboard.signalsciences.net/support) might help us to better categorize and prioritize your request.
