### ISSUE TITLE
regex match operator does not exist

### ISSUE THREAD

**Issue by frankw2** [signalsciences/terraform-provider-sigsci#62]
the regex operator does not seem to exist even though it is available in the web version.

**Comment by mb38291** [comment]
There are a lot of inconsistencies, I think. It's "matches" for the example below:

```
conditions {
    type = "single"
    field = "name"
    operator = "matches"
    value = "^/abc/[0-9]+/xyz$"
}
```

**Comment by shawnps** [comment]
@frankw2 thanks for the issue. 

@mb38291 is correct that the operator is `"matches"`. 

I was able to create a site rule with a regex matching the request header like so:

```
resource "sigsci_site_rule" "test-rules-regexp" {
  site_short_name = "[site short name]"
  type            = "request"
  group_operator  = "all"
  enabled         = true
  reason          = "test reason"
  expiration      = ""

  conditions {
    type           = "multival"
    field          = "requestHeader"
    group_operator = "all"
    operator       = "exists"

    conditions {
      type     = "single"
      field    = "name"
      operator = "matches"
      value    = "^/abc/[0-9]+/xyz$"
    }   
  }

  actions {
    type = "block"
  }
}
```

However our [API docs](https://docs.fastly.com/signalsciences/api/#_corps__corpName__sites__siteName__rules_post) do not specify `matches` as a valid operator. 

I'll close this issue and make an internal ticket to add `matches` to the API docs. Please reopen this issue if I misunderstood 👍

**Comment by frankw2** [comment]
great thanks!
