### ISSUE TITLE
Interval and threshold are not marked as a required field for sigsci_site_alert

### ISSUE THREAD

**Issue by singhprincejeet** [signalsciences/terraform-provider-sigsci#64]
In the [documentation](https://registry.terraform.io/providers/signalsciences/sigsci/latest/docs/resources/site_alert), interval and threshold are not marked as required fields but while applying the change in terraform, you get the followig errors: 
* `Error: Interval must be 1, 10 or 60`. 
* `Error: Threshold must be between 1 and 10000`

It would be nice to mention in the doc that interval and threshold are required fields.

**Comment by shawnps** [comment]
Fixed in https://github.com/signalsciences/terraform-provider-sigsci/pull/117
