### ISSUE TITLE
Unable to change/update rate limit rule

### ISSUE THREAD

**Issue by powtor** [signalsciences/terraform-provider-sigsci#68]
When I tried to update the rate limit rule a got an error below. It should first delete the rule and next recreate it.

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.site_rule.sigsci_site_rule.rule will be updated in-place
  ~ resource "sigsci_site_rule" "rule" {
        id              = "69c2000000001d2c45c95"
      ~ rate_limit      = {
          ~ "threshold" = "7" -> "8"
            # (2 unchanged elements hidden)
        }
        # (6 unchanged attributes hidden)
        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
module.site_rule.sigsci_site_rule.rule: Modifying...
╷
│ Error: Validation failed - rate limit data required for rate limit rule
│ 
│   with module.site_rule.sigsci_site_rule.rule,
│   on ../../modules/site_rule/main.tf line 5, in resource "sigsci_site_rule" "rule":
│    5: resource "sigsci_site_rule" "rule" {
│ 
╵
```

**Comment by loxal** [comment]
I can confirm: broken in `v0.5.0` worked fine in a previous version though.

**Comment by loxal** [comment]
@holy-moly-555 can you confirm this issue with the latest version 1.1.0?
I've created an [internal issue](https://fastly.atlassian.net/browse/SECURE-107) to better track the progress.

**Comment by holy-moly-555** [comment]
@loxal yes, I can confirm that this issue still occurs with provider version 1.1.0.
After the resource is created I am no longer able to update it via Terraform.
The error message is the same that @powtor posted.

**Comment by shawnps** [comment]
@powtor @holy-moly-555 Apologies for the delay -- I've merged a fix for this here:

https://github.com/signalsciences/terraform-provider-sigsci/pull/98

We were setting the rate limit attributes when creating a rule, but not when updating one.

I tested this change on both a request rule (which has no rate limit attributes) and a rate limit rule and both were updated successfully (rate limit attributes such as threshold and interval were updated properly in the latter).

I'll release v1.2.2 soon which will contain this fix. Please reopen the issue and assign to me if it doesn't work as expected.

**Comment by holy-moly-555** [comment]
@shawnps 

it's not working for the `requestlogging` attribute ...

Also, I'm quite disappointed & frustrated that you guys don't update the documentation for new attributes etc. ...
For example: https://registry.terraform.io/providers/signalsciences/sigsci/latest/docs/resources/site_alert

The resource documentation does not contain the `block_duration_seconds` attribute that was added with version 1.2.0

**Comment by holy-moly-555** [comment]
@shawnps @loxal 

Just realized that this is a bug of another kind (but still related to the original issue).
In the web console there is no way to specify the request Logging for rate limit rules (like for the normal request rules).

However, doing a plan on a rate limit rule without changing anything outputs:

```
# sigsci_site_rule.limit_XXX will be updated in-place
  ~ resource "sigsci_site_rule" "limit_XXX" {
        id              = "XXX"
      + requestlogging  = "sampled"
        # (7 unchanged attributes hidden)

        # (5 unchanged blocks hidden)
    }
```

Even after an apply, the change occurrs.

**Comment by shawnps** [comment]
> > Also, I'm quite disappointed & frustrated that you guys don't update the documentation for new attributes etc. ...
> For example: https://registry.terraform.io/providers/signalsciences/sigsci/latest/docs/resources/site_alert
> The resource documentation does not contain the `block_duration_seconds` attribute that was added with version 1.2.0

@holy-moly-555 

Sorry about that, you are absolutely right that we need to make sure the docs stay up to date. I will take a look at that.

Also you're right that we're defaulting to updating `requestlogging` even if the rule type does not support modifying it:

https://github.com/signalsciences/terraform-provider-sigsci/blob/main/provider/resource_site_rule.go#L54

I believe removing this `Default` should fix that but I'll do some testing to confirm.
