### ISSUE TITLE
Support custom duration for site alert action

### ISSUE THREAD

**Issue by holy-moly-555** [signalsciences/terraform-provider-sigsci#80]
### Issue

In the web console I am able to set the action duration of a site alert between 10 minutes and 1 day (default).
However the Terraform provider does not support other durations than the default of 1 day.

### Desired solution

Provide a non-required setting to set a custom duration as in the web console.

**Comment by shawnps** [comment]
@holy-moly-555 thanks for the issue -- I am working on this here: https://github.com/signalsciences/terraform-provider-sigsci/pull/81.

It also requires a change to `go-sigsci`: https://github.com/signalsciences/go-sigsci/pull/33.

**Comment by shawnps** [comment]
@holy-moly-555 I'm going to close this since I believe https://github.com/signalsciences/terraform-provider-sigsci/pull/81 fixed it, but please reopen this issue if it's still an issue.
