### ISSUE TITLE
Error: : invalid or unknown key: id 

### ISSUE THREAD

**Issue by JazSingh05** [signalsciences/terraform-provider-sigsci#86]
I am getting an "Error: : invalid or unknown key: id " when referencing the sigsci_site_list resource . Occurs when i reference the an id parameter in the resource. 

The [docs](https://registry.terraform.io/providers/signalsciences/sigsci/latest/docs/resources/site_list#id) mention that an ID parameter can be set, but the [code](https://github.com/DataDog/terraform-provider-datadog/blob/master/datadog/resource_datadog_dashboard.go) doesn't actually have that parameter. So either the docs need to be updated or the provider does, I'm just not sure which.

I saw another similar issue referencing how "id" is a protected variable in terraform: https://github.com/DataDog/terraform-provider-datadog/issues/947

**Comment by shawnps** [comment]
@JazSingh05 could you provide an example? If you're trying to set the id attribute yourself, I'm not sure that will work because the API creates the ID for us. 

You should still be able to reference the id in your terraform like this:

```
resource "sigsci_site_list" "mylist" {
  name            = "mylistname"
  site_short_name = "siteshortname"
  type            = "ip"
  description     = "Some IPs"
  entries = [
    "1.2.3.4",
    "1.2.3.5",
  ]
}

resource "sigsci_site_rule" "test-rule" {
  site_short_name = "siteshortname"
  type            = "request"
  group_operator  = "any"
  enabled         = true
  reason          = "Test reason"
  expiration      = ""

  conditions {
    type     = "single"
    field    = "ip"
    operator = "inList"
    value    = sigsci_site_list.mylist.id
  }

  actions {
    type = "allow"
  }
}
```

**Comment by shawnps** [comment]
@JazSingh05 I'm going to close this out but please reopen if I've misunderstood the problem.
