### ISSUE TITLE
unable to set provider 

### ISSUE THREAD

**Issue by Voidwalker0x79** [signalsciences/terraform-provider-sigsci#87]
Following the provider setup docs for signalsciecnes/sigsci version 1.1.0
```
terraform {
  required_providers {
    sigsci = {
      source  = "signalsciences/sigsci"
    }
  }
}

provider "sigsci" {
  email    = var.email
  auth_token = var.auth_token
  corp     = var.corp
}
```
I am getting the following on terraform plan.
`Error: Invalid resource request
with provider["registry.terraform.io/signalsciences/sigsci"],
on main.tf line 9, in provider "sigsci":
 9: provider "sigsci" {}
`

Any ideas on how to resolve? Running
```
Terraform v1.3.5
on darwin_arm64
+ provider registry.terraform.io/signalsciences/sigsci v1.1.0
```

**Comment by Voidwalker0x79** [comment]
For clarity sake,
I tried hardcoding the provider version going back 6 months, with the same result.

**Comment by rickyaustin** [comment]
The issue was the value of `var.corp` contained an uppercase letter. We can mark this as resolved

**Comment by shawnps** [comment]
@Voidwalker0x79 @rickyaustin based on https://github.com/signalsciences/terraform-provider-sigsci/issues/87#issuecomment-1320527412 it looks like the issue was resolved, so I'll close this issue. Please reopen if I misunderstood.
