### ISSUE TITLE
The `requestlogging` field causes validation issues for the `sigsci_site_rule` resource on 1.2.0

### ISSUE THREAD

**Issue by mike-carey** [signalsciences/terraform-provider-sigsci#89]
When upgrading the provider from 1.1.0 to 1.2.0, we receive the following error on plan:

```
╷
│ Error: Internal validation of the provider failed! This is always a bug
│ with the provider itself, and not a user issue. Please report
│ this bug:
│
│ 1 error occurred:
│ 	* resource sigsci_site_rule: requestlogging: One of optional, required, or computed must be set
│
│
│
│   with provider["registry.terraform.io/signalsciences/sigsci"],
│   on versions.tf line 23, in provider "sigsci":
│   23: provider "sigsci" {
│
╵
```

It looks like #84 added requestlogging but I see no documentation on it in the docs.  I see that the argument is set to optional, per the code: https://github.com/signalsciences/terraform-provider-sigsci/pull/84/files#diff-3fdca6eb31998d66d841e62a524387e655ca5024bdd83939355fbfa714d7432fR53.

**Comment by roryscarson** [comment]
a workaround is to pin the provider version to 1.1.0, once #90 is deployed this should fix the validator and we should be able to remove the version pin. 

```
    sigsci = {
      source = "signalsciences/sigsci"
      version = "~> 1.1.0"
    }
```

**Comment by shawnps** [comment]
Hi everyone, very sorry about this issue.

Thanks to @ponkio-o I've merged https://github.com/signalsciences/terraform-provider-sigsci/pull/90 and will tag a new release which should get propagated to the TF Registry. I'll make it version `v1.2.1`.

Please let me know if that doesn't fix the issue for you.

Thank you for your patience!
